cmake: Disable format-overflow warning as error
gcc10 complains about a check which could potentially be null

build/inc/interface/vcos/vcos_logging.h:234:88: error: '%s' directive argument is null [-Werror=format-overflow=]
  234 | #  define _VCOS_LOG_X(cat, _level, fmt...)   do { if (vcos_is_log_enabled(cat,_level)) vcos_log_impl(cat,_level,fmt); } while (0)
      |                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A potential fix would be to check for fmt not being null but lets leave
that to experts

Upstream-Status: Pending

Signed-off-by: Khem Raj <raj.khem@gmail.com>