mmal: Add missing struct field definition (#355)
Fixes

util/mmal_il.c:776:35: error:
      implicit conversion from enumeration type 'enum OMX_BAYERORDERTYPE' to different enumeration type
      'OMX_COLOR_FORMATTYPE' (aka 'enum OMX_COLOR_FORMATTYPE') [-Werror,-Wenum-conversion]
   {MMAL_ENCODING_UNKNOWN,        OMX_BayerOrderMax}

Signed-off-by: Khem Raj <raj.khem@gmail.com>